### ISSUE TITLE
Password for pem key

### ISSUE THREAD

**Issue by LightTemplar** [majal/maj-scripts#1]
Hi! Could you please modify your vboxsign script so I could provide a pass to private key?
I tried to add 
`read -s -p "Password for key: " KBUILD_SIGN_PIN`
but it was somewhere wrong, as I get 
 `At main.c:224:`
`- SSL error:0907B068:PEM routines:PEM_READ_BIO_PRIVATEKEY:bad password read: pem_pkey.c:117`
`sign-file: ./MOK.priv: No such file or directory`

if I run sign-file with `env KBUILD_SIGN_PIN=mypass` it works flawlessly.

**Comment by majal** [comment]
Hello. Here is the proposed change in the main script:
https://github.com/Majal/maj-scripts/blob/Majal-proposed-patches/vboxsign

Just uncomment the block for KBUILD_SIGN_PIN. I haven't tested this yet as I don't use key encryption this way. If it works, please give feedback so that we can merge this proposed change to the main script. Thank you.

**Comment by LightTemplar** [comment]
It worked! Thank you a lot! 
It can be merged with main.
